services:
  passenger-db:
    image: postgres:15-alpine
    container_name: passenger-db
    environment:
      POSTGRES_DB: passenger_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5550:5432"
    volumes:
      - passenger_data:/var/lib/postgresql/data

  driver-db:
    image: postgres:15-alpine
    container_name: driver-db
    environment:
      POSTGRES_DB: driver_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5551:5432"
    volumes:
      - driver_data:/var/lib/postgresql/data

  ride-db:
    image: postgres:15-alpine
    container_name: ride-db
    environment:
      POSTGRES_DB: ride_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5552:5432"
    volumes:
      - ride_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  passenger_data:
  driver_data:
  redis_data:
  ride_data: