services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_EXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_EXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_EXT://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  discovery:
    build: ./discovery
    ports:
      - "8761:8761"

  passenger_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - passenger_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s

  passenger-service:
    build: ./passenger-service
    depends_on:
      discovery:
        condition: service_started
      passenger_db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://passenger_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/migration/db2.xml
    ports:
      - "8080:8080"

  driver_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"
    volumes:
      - driver_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s

  driver-service:
    build: ./driver-service
    depends_on:
      driver_db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://driver_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/migration/db1.yml
    ports:
      - "8081:8080"

  rating_db:
    container_name: rating_db
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111
    volumes:
      - rating_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://root:1111@localhost:27017/admin
      interval: 10s
      timeout: 10s
      retries: 5

  rating-service:
    build: ./rating-service
    depends_on:
      discovery:
        condition: service_started
      rating_db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:1111@rating_db:27017/ride?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_APPLICATION_NAME: rating-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    ports:
      - "8082:8080"

  ride_db:
    container_name: ride_db
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111
    volumes:
      - ride_data:/data/db
    ports:
      - "27018:27017"
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://root:1111@localhost:27017/admin
      interval: 10s
      timeout: 10s
      retries: 5

  ride-service:
    build: ./ride-service
    depends_on:
      ride_db:
        condition: service_healthy
      kafka:
        condition: service_started
      discovery:
        condition: service_started
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:1111@ride_db:27017/ride?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_APPLICATION_NAME: ride-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    ports:
      - "8083:8080"

  payment_db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
    ports:
      - "6543:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      start_period: 10s

  payment-service:
    build: ./payment-service
    depends_on:
      payment_db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1111
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/migration/db3.yml
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_APPLICATION_NAME: payment-service
    ports:
      - "8084:8080"

  gateway:
    build: ./gateway
    depends_on:
      discovery:
        condition: service_started
    environment:
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWERCASE_SERVICE_ID: "true"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery:8761/eureka
    ports:
      - "8000:8080"

volumes:
  passenger_data:
  payment_data:
  driver_data:
  ride_data:
  rating_data:
