services:
  passenger-db:
    image: postgres:15-alpine
    container_name: passenger-db
    environment:
      POSTGRES_DB: passenger_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5550:5432"
    volumes:
      - passenger_data:/var/lib/postgresql/data

volumes:
  passenger_data: