spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service-go
              uri: http://localhost:8885
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /api/auth/$1

            - id: passenger-service
              uri: lb://PASSENGER-SERVICE
              predicates:
                - Path=/passengers/**
              filters:
                - RewritePath=/passengers/(?<segment>.*), /api/v1/passengers/$1

            - id: driver-service
              uri: lb://DRIVER-SERVICE
              predicates:
                - Path=/drivers/**
              filters:
                - RewritePath=/drivers/(?<segment>.*), /api/v1/drivers/$1

            - id: ride-service
              uri: lb://RIDE-SERVICE
              predicates:
                - Path=/rides/**
              filters:
                - RewritePath=/rides/(?<segment>.*), /api/v1/rides/$1

            - id: rating-service
              uri: lb://RATING-SERVICE
              predicates:
                - Path=/ratings/**
              filters:
                - RewritePath=/ratings/(?<segment>.*), /api/v1/ratings/$1

            - id: payment-methods-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-methods/**
              filters:
                - RewritePath=/payment-methods/(?<segment>.*), /api/v1/payment-methods/$1

            - id: accounts-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/accounts/**
              filters:
                - RewritePath=/accounts/(?<segment>.*), /api/v1/accounts/$1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080