spring:
  application:
    name: rating-service

  mongodb:
    uri: mongodb://admin:1111@localhost:27017/rating_db?authSource=admin
    representation:
      uuid: standard

  data:
    mongodb:
      auto-index-creation: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rating-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    topic:
      rides.users: "rides.users"
    event:
      user-created: "userCreated"

server:
  port: 8884

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
