server:
  port: 8883

spring:
  application:
    name: payment-service

  Kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ride-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://localhost:5553/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
    enabled: true
    default-schema: public

stripe:
  api:
    key: ${STRIPE_API_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/