server:
  port: 8080

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://payment_db:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/migration/db3.yml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery:8761/eureka}