spring:
  kafka:
    bootstrap-servers: localhost:29092
  application:
    name: driver-service
  liquibase:
    change-log: classpath:db/migration/db1.yml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:54321/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    com.example.driver_service.client.RideServiceClient: DEBUG
