spring:
  kafka:
    bootstrap-servers: kafka:9092
  application:
    name: ride-service
  data:
    mongodb:
      uri: mongodb://root:1111@ride_db:27017/ride?authSource=admin

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: ride-service