spring:
  application:
    name: ride-service

  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml

  Kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ride-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: localhost
      port: 6379
      password: 1111
      connect-timeout: 2s
      client-name: driver-service
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  datasource:
    url: jdbc:postgresql://localhost:5552/ride_db
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8882

ors:
  api:
    key: ${ORS_API_KEY}
  url: "https://api.openrouteservice.org/v2/directions/driving-car"

app:
  Kafka:
    ride-topic: "ride_events_topic"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/