spring:
  liquibase:
    change-log: classpath:db/migration/db2.xml
  datasource:
    url: jdbc:postgresql://passenger_db:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8080