spring:
  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml

  application:
    name: passenger-service

  datasource:
    url: jdbc:postgresql://localhost:5550/passenger_db
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: passenger-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    topic:
      rides.users: "rides.users"
    event:
      user-created: "userCreated"

server:
  port: 8880

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      access: read_only

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/