spring:
  application:
    name: passenger-service
  liquibase:
    change-log: classpath:db/migration/db2.xml
  datasource:
    url: jdbc:postgresql://passenger_db:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080